# Generated by Django 5.0.6 on 2024-06-18 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="product",
            new_name="products",
        ),
    ]
