# Generated by Django 5.0.6 on 2024-06-18 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_rename_product_order_products"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="products",
            new_name="product",
        ),
    ]
