name: Python Pull Request Workflow
on: [pull_request]
jobs:

  qa:
    name: Quality check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install poetry
        run: |
          pip install -U pip
          pip install poetry
          poetry config virtualenvs.create false 
          poetry install
      - name: Install dependencies
        run: |
          poetry add django-extensions
      - name: Test
        run: |
          poetry run python manage.py test
      - name: Wemake Python Stylguide
        uses: Wemake-services/wemake-python-styleguide@0.16.0
        continue-on-error: true
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
